### ISSUE TITLE
error on startup 

### ISSUE THREAD

**Issue by ftoledo** [M-griffin/EtherTerm#60]
hi i just compile the feature/0.4.10-alpha branch:

```
ragnarok@ragnarok:/tmp/EtherTerm/build$ gdb EtherTerm 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from EtherTerm...done.
r(gdb) r
Starting program: /tmp/EtherTerm/build/EtherTerm 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
EtherTerm Working directory is: /tmp/EtherTerm/build/
SessionManager Created
Interface Created
[New Thread 0x7fffeeabd700 (LWP 14897)]
WindowManager Created!
Creating Window and Renderer!
SurfaceManager Created!
Session Created!
Joined SessionManager
InputHandler Created
Renderer Created
A Surface was Created!
A Surface was Created!
A Surface was Created!
A Surface was Created!
A Surface was Created!
A Texture was Created!
ScreenBuffer Created!
SequenceParser Created
SequenceDecoder Created
Protocol
Fontset Created!
MenuConfig Created!
MenuIO Created!
MenuFunction Created!
MenuManager Created!
Reading Theme: 
Reading file: /tmp/EtherTerm/build/assets/directory/directory.ini
 $$$ FONT_SET topazPlus-8x16.bmp
readDialDirectory - Done
m_system_entries.size(): 0
parseHeader()
sFONT_SET: topazPlus-8x16.bmp
Error, Fontsets not loaded!
EtherTerm: ../src/menu_manager.cpp:97: void MenuManager::parseHeader(std::__cxx11::string): Assertion `false' failed.

Thread 1 "EtherTerm" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No existe el fichero o el directorio.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff67a942a in __GI_abort () at abort.c:89
#2  0x00007ffff67a0e67 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x5555555fa60d "false", 
    file=file@entry=0x5555555fa5f5 "../src/menu_manager.cpp", line=line@entry=97, 
    function=function@entry=0x5555555fa900 <MenuManager::parseHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::__PRETTY_FUNCTION__> "void MenuManager::parseHeader(std::__cxx11::string)") at assert.c:92
#3  0x00007ffff67a0f12 in __GI___assert_fail (assertion=0x5555555fa60d "false", file=0x5555555fa5f5 "../src/menu_manager.cpp", line=97, 
    function=0x5555555fa900 <MenuManager::parseHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::__PRETTY_FUNCTION__> "void MenuManager::parseHeader(std::__cxx11::string)") at assert.c:101
#4  0x000055555558a1c1 in MenuManager::parseHeader (this=0x55555744d480, file_name="default_theme.ans") at ../src/menu_manager.cpp:97
#5  0x000055555558b9ae in MenuManager::setupDialDirectory (this=0x55555744d480) at ../src/menu_manager.cpp:694
#6  0x0000555555575872 in Session::startMenuInstance (this=0x5555558ae000) at ../src/session.hpp:470
#7  0x00005555555761c2 in Interface::spawnLocalSession (this=0x55555585a5c0) at ../src/interface.hpp:169
#8  0x0000555555575d11 in Interface::startup (this=0x55555585a5c0) at ../src/interface.hpp:66
#9  0x00005555555738da in main (argc=1, argv=0x7fffffffdee8) at ../src/main.cpp:221
(gdb) 

```

**Comment by M-griffin** [comment]
Hi ftoledo,  Thanks for checking it out.  The 4.10 Branch is a WIP and i'm still in the middle of ripping stuff out and replacing stuff so it's not runnable yet.  Once it's all set it will get merged into the master branch.

**Comment by ftoledo** [comment]
hi @M-griffin yes i know! i just reported because i will package it for debian when released!
=)

**Comment by M-griffin** [comment]
Oh awesome, thank you for the support!  I do recommended only packaging master branch, other branches are more for development work and most of the time if stuff is getting reworked it could be broken otherwise.. but no worries.. nice to see some feedback once in a while. :)
